# See https://github.com/binder-examples/conda
name: qtplaskin-env
channels:
- conda-forge
dependencies:
- python=3.8
- numpy
- scipy
- matplotlib
- pandas
- h5py
- pytest
- pip
- pip:
  - mpldatacursor